### ISSUE TITLE
No separation between Enumerable and FinitelyEnumerable

### ISSUE THREAD

**Issue by jbrownson** [purescript/purescript-enums#10]
In Haskell's Data.Enumerable there's a distinction between Enumerable and FinitelyEnumerable. This allows for example to have an Enumerable instance for (FinitelyEnumerable a) => List a which is something I'd be interested in at the moment.

It would be possible to do this w/o breaking anything if instead of adding FinitelyEnumerable and changing Enumerable we added the opposite, not sure what it would be called, but maybe NonfinitelyEnumerable or something.

Would you be open to a pull request?

**Comment by paf31** [comment]
I'd love to change this, and I'd prefer to break it and have `Finite a <= Enum a`.
