### ISSUE TITLE
Inconsistent behavior of enumFromTo for bounded enums

### ISSUE THREAD

**Issue by sharkdp** [purescript/purescript-enums#15]
With the canonical `Enum` instance for the following data type
``` purs
data T = A | B | C | D
```
I get:
``` purs
> enumFromTo A A :: Array T
[A]
> enumFromTo A B :: Array T
[A,B]
> enumFromTo A C :: Array T
[A,B,C]
> enumFromTo A D :: Array T
[A,B,C]
```

The last one returns a wrong result with the current implementation for `enumFromTo` because the unfoldr-function calls `succ D`, which short-circuits in the Maybe monad and breaks the unfoldr 'loop'.

Note: this only fails for bounded Enums

**Comment by garyb** [comment]
Good catch.

What do you mean it only fails for bounded enums though? Have you got an example of a non-bounded enum that it wouldn't fail for?

**Comment by sharkdp** [comment]
> What do you mean it only fails for bounded enums though? Have you got an example of a non-bounded enum that it wouldn't fail for?

I believe the error only appears if the `upper` bound in the `enumFromTo lower upper` call equals `top` (alternatively, if `succ upper = Nothing`). If a data type were truly unbounded, the error would never appear.
