### ISSUE TITLE
BoundedEnum instance for Int has invalid cardinality

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-enums#25]
Yes, `Int` violates a lot of typeclass laws... But the `BoundedEnum` instance having a cardinality of -1 seems particularly egregious. It certainly trapped me. Is this instance worth keeping despite that?

**Comment by garyb** [comment]
@paf31 what do you think we should do here? I guess we should use a `Nat` for cardinality really...

We could drop the instance, or use `Number` instead of `Int` perhaps? 😕

**Comment by paf31** [comment]
I think we should just remove it for now.
