### ISSUE TITLE
Incorrect assumptions from BoundedEnum laws.

### ISSUE THREAD

**Issue by MaloJaffre** [purescript/purescript-enums#27]
These instances / functions all require that `fromEnum bottom == 0` to work properly,  although there is no law to enforce this:
- `BoundedEnum (Maybe a)`
- `BoundedEnum (Either a b)`
- `BoundedEnum (Tuple a b)`
- `defaultToEnum`
- `defaultFromEnum`
- `toEnumWithDefaults`

Two ways to fix this:

- Add `fromEnum bottom == 0` law, this is commonly true, but e. g. not in [purescript-dom](https://github.com/purescript-contrib/purescript-dom/blob/master/src/DOM/Node/NodeType.purs#L55)

- Rework these instances / functions to work in these edges cases, adding / substracting `fromEnum bottom` in `fromEnum` / `toEnum` respectively.

Unfortunately these are IMO breaking changes.

**Comment by garyb** [comment]
Did you see #23? It's been a while since I looked at that discussion, but I think it covers similar territory.

**Comment by MaloJaffre** [comment]
#23 is more about laws of `pred` and `succ` in `BoundedEnum` context while this is about what values are permissible for `fromEnum bottom` (currently any number, while only `0` work for some instances / functions)

**Comment by garyb** [comment]
This will be somewhat resolved in the release for the 0.12 compiler - I've removed the offending instances for now (they are possible, but they're going to be kinda gnarly and probably slow), and added notes to the functions that make assumptions that `fromEnum bottom = 0`.

Thanks!
