### ISSUE TITLE
upFromIncluding :: ∀ a u. Enum a => Unfoldable u => a -> NonEmpty u a

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-enums#30]
Thoughts on adding this?
``` purescript
upFromIncluding :: ∀ a u. Enum a => Unfoldable u => a -> NonEmpty u a
upFromIncluding x = NonEmpty x $ upFrom x
```

**Comment by paf31** [comment]
👍 I'm surprised `upFrom x` doesn't start at `x` actually.

**Comment by safareli** [comment]
> I'm surprised `upFrom x` doesn't start at x actually.

Yes that was not expecting for me too. but this way upFromIncluding has much correct type :d
