### ISSUE TITLE
move Cardinality to type level

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-enums#35]
Once https://github.com/purescript/purescript/pull/3058 is merged, perhaps `BoundedEnum` could get a new param, with its cardinality defined at type level, with a fundep from the type to the cardinality.

**Comment by garyb** [comment]
Does that give us any advantages? It also kinda clutters up the constraint, since we don't have associated types.

**Comment by matthewleon** [comment]
Honestly this might be excessive zeal for safety on my part. My thinking was that it allows this `Range` idea that I'm working on to have a type-level natural as well, which would mean that you could get an efficient `toEnum'` that lacks a `Maybe`, if you were to use the types from modular-arithmetic. But really, that is probably getting to the point of being cumbersome. And it could be defined in a separate lib, too.

If I can't think of something better here, I could close this.

**Comment by matthewleon** [comment]
I think I can accomplish what I'm looking for without this.
