### ISSUE TITLE
Why succ returns Maybe?

### ISSUE THREAD

**Issue by Masynchin** [purescript/purescript-enums#53]
Why can't I create Enum with `succ:: a -> a`? For example, it can describe cycled boolean enum, where `succ True` returns `False` and `succ succ True` returns `True`.

**Comment by garyb** [comment]
That would break the laws of `Enum` as defined here, so I guess the answer is "because we chose `Enum` to mean something that is incompatible with this idea". :wink:

Maybe `cyclicSucc` / `cyclicPred` functions could be defined in terms of `BoundedEnum`? That way they're not breaking any laws and they're taking advantage of the existing definitions.

(Also I assume your case isn't actually `Boolean`, since you could use `not` for that.)

**Comment by JordanMartinez** [comment]
I think there might be room for a `CyclicalBoundedEnum` type class:
```
class CyclicalBoundedEnum where
  skip :: Int -> a -> a
  cyclicalBottom :: a
  cyclicalTop :: a
```
If something is cyclical, then is it likely that `succ`/`pred` could be succeeded with `skip`?

**Comment by garyb** [comment]
> I think there might be room for a `CyclicalBoundedEnum` type class:

I thought about that too, but I think the class would be basically lawless, and I'm not sure it gives you anything that couldn't be defined in terms of `BoundedEnum` already. Just fewer instances to implement I guess.

**Comment by Masynchin** [comment]
> Also I assume your case isn't actually `Boolean`, since you could use `not` for that.

My thoughts were about tracks list, where succ of last track returns first track. With Boolean example I tried to show that Maybe only needs for bounds, when in other realization it can return min bound instead. I also have checked how it is done in Haskell - it has signature `succ :: a -> a`. I don't have much experience in Haskell, but think it is what I wrote above.

**Comment by garyb** [comment]
Yeah, `Enum` in Haskell is quite different, it's only really intended for statically sized things in PureScript. Also its version of `succ` is still partial, if you try `succ True` it raises an error, so it's just not exposed in the type the way it is here.

For something dynamic like a track list I'd perhaps do something with an infinite (lazy) list, use a zipper, or just a pair of my own functions to handle it.

**Comment by Masynchin** [comment]
> For something dynamic like a track list I'd perhaps do something with an infinite (lazy) list, use a zipper, or just a pair of my own functions to handle it.

Yeah, I currently do `Track` type with `rotate :: Track -> Track` function. Maybe `Enum` for `Track` is not that suitable as my own type, an interesting idea at start. @garyb and @JordanMartinez thanks for help!
