### ISSUE TITLE
Overlapping instances found

### ISSUE THREAD

**Issue by rubenmoor** [purescript/purescript-enums#9]
Is the problem just this, or are my dependencies messed up?

Compiling Data.Enum
Error found:
Error in module Data.Enum:
Error in value declaration enumChar:
Error at /home/ruben/code/holger/hermit/bower_components/purescript-enums/src/Data/Enum.purs line 113, column 1 - line 121, column 1:
  Overlapping instances found for Prelude.Bounded Prim.Char:
  Data.Char.boundedChar
  Prelude.boundedChar

**Comment by garyb** [comment]
It's not your fault, but yeah the dependencies are messed up - the `Data.Char.boundedChar` is an orphan instance, so we removed it from there and added it to `Prelude` (also it was incorrect). The prelude version was bumped as a patch release, but the update to strings was a breaking change release, but we've also updated everything in core that depended on strings so hopefully you should be able to update your dependency versions and everything should work out...

@paf31 looks like you were right though, maybe we should have bumped `Prelude` after all :cry: I'm not sure why the orphan instance error is appearing here when it seemed not to when I tested compiling new strings with the old prelude.

**Comment by paf31** [comment]
Does this happen after `enums` is updated?

**Comment by garyb** [comment]
[It shouldn't](https://github.com/purescript/purescript-enums/commit/94188c75deeb55e42d3ef3634f31c2a6dbeab2ba)

**Comment by paf31** [comment]
But does it? :smile:

**Comment by garyb** [comment]
Not for me :wink: - I ran the post-travis-test-everything locally after updating the libraries.

**Comment by paf31** [comment]
Maybe a cache issue then?

**Comment by rubenmoor** [comment]
I ran

    $ bower cache clean
    $ bower update

Still got the issue upon compiling.

**Comment by garyb** [comment]
`bower update` won't update to the new version automatically as the new version is incompatible with the old - you'll need to update your `purescript-enums` dependency to `^0.7.0` (or whatever it is that is pulling purescript-enums in).

**Comment by rubenmoor** [comment]
oh sure. Unfortunately, i end up with `purescript-enums 0.50` automatically. My dep tree looks like this

    purescript-node-fs 0.7.1 (or master)
        requires purescript-datetime 0.6.0
            requires purescript-enums 0.5.0

Adding

    "purescript-enums": "^0.7.0"

to `dependencies` results in conflicts for `bower update` and quite regardless of my choice I run into the overlapping instances error. And adding the 0.7.0 to `resolutions` does nothing (not even a conflict during `bower update`)

**Comment by garyb** [comment]
Ahh ok! I'll update `purescript-node-fs`. I forgot about the projects in `purescript-node`.

**Comment by garyb** [comment]
If you bump your `purescript-node-fs` to `v0.8.0` it should work out now, hopefully.

**Comment by rubenmoor** [comment]
Now I run into issues with my other dependencies:

Unable to find a suitable version for purescript-foreign, please choose one:
    1) purescript-foreign#^0.5.0 which resolved to 0.5.1 and is required by purescript-affjax#0.4.0, purescript-halogen#0ed8df5900
    2) purescript-foreign#^0.7.0 which resolved to 0.7.0 and is required by purescript-node-fs#0.8.0

I'll keep trying. Is there a standard way to resolve this?

**Comment by rubenmoor** [comment]
If I'm not mistaken, this is rather hopeless, or at least I lack overview on why and how packages depend on the older versions of `purescript-strings` and I am not able to resolve my issue by trying out different combinations.

Unable to find a suitable version for purescript-strings, please choose one:
    1) purescript-strings#^0.5.0 which resolved to 0.5.5 and is required by purescript-enums#0.5.0, purescript-simple-dom#0.1.0, purescript-string-parsers#03d8277615
    2) purescript-strings#~0.5.3 which resolved to 0.5.5 and is required by purescript-argonaut-codecs#0.1.0, purescript-foreign#0.5.1
    3) purescript-strings#^0.5.2 which resolved to 0.5.5 and is required by purescript-css#150ae110d3
    4) purescript-strings#^0.7.0 which resolved to 0.7.0 and is required by purescript-enums#0.7.0, purescript-foreign#0.7.0

**Comment by rubenmoor** [comment]
Any idea for a workaround?

**Comment by garyb** [comment]
Ok, for the time being as an alternative, what happens if you stick to your original set of dependencies but add `"purescript-prelude": "0.1.1"`? This should prevent bower from pulling in `v0.1.2` of the prelude which has the new instance in it.

In the long run all the stuff you're depending on will need updating anyway, as the old version of `purescript-strings` will not work with the most recently compiler release (v0.7.3, released yesterday). Some of them I'm responsible for anyway - namely `affjax` and `halogen`, so they will be updated in the near future.

**Comment by rubenmoor** [comment]
That works for me. Thanks!

**Comment by garyb** [comment]
Great, sorry you had such trouble with it!

**Comment by Thimoteus** [comment]
For some reason that fix doesn't work for me. I have purescript-prelude#0.1.1 in my bower.json, and `grep -r "Enum Char" bower_components/*` only gives me the instance in purescript-enums. I've removed bower_componenets/ and done bower cache clean many times, can't seem to get around it.

**Comment by garyb** [comment]
@Thimoteus `purescript-strings` pre-v0.7.0 combined with `purescript-prelude` v0.1.2 is the "real" culprit here, so if you have the older strings as a dependency that's where the issue will be coming from.

**Comment by Thimoteus** [comment]
I added purescript-strings#0.7.0 as a dependency but the problem persists. I'm out of ideas, shouldn't it not happen if I have purescript-strings before 0.7.0 *and* purescript-prelude 0.1.1?

**Comment by garyb** [comment]
Oh, sorry, yep, prelude v0.1.1 should be fine with any version of strings.

What do you get from `bower list` after installing now?

**Comment by Thimoteus** [comment]
[Here's the dependency tree](https://gist.github.com/Thimoteus/21641a9d4909eb5b0d27)

**Comment by garyb** [comment]
:(

Did you try removing the `output` folder as well before compiling?

**Comment by Thimoteus** [comment]
Ahh, that worked. I always forget about the output folder ...
